### ISSUE TITLE
Question/Creating new challenge pack

### ISSUE THREAD

**Issue by patrickmelville** [Simonomi/Coding-Royale#1]
When i select files to use with the "Challenge pack creator.exe"... 

Should I move that folder into the Challenge Packs folder afterwards?

After I selected the files I wanted to test for this, the folder that was created was put in the main project folder, not the challenge pack folder.

**Comment by simonomi** [comment]
The challenge packs folder in the root of the repository is for sample ones, the challenge packs folder in the server folder is the one used when hosting the server, the challenge pack creator creates the pack, then you put it in the folder you want
TLDR: yes

**Comment by patrickmelville** [comment]
ok. thanks. ill set all that up and put in a pull request a little later this weekend for some more examples to test everything out with.
